export const cases = [
  {
    'name': 'inline template',
    'scopeName': 'inline-template.ng',
    'grammarFiles': [
      'syntaxes/inline-template.json',
      'syntaxes/template.json',
      'syntaxes/expression.json',
    ],
    'testFile': 'syntaxes/test/data/inline-template.ts',
  },
  {
    'name': 'inline styles',
    'scopeName': 'inline-styles.ng',
    'grammarFiles': ['syntaxes/inline-styles.json', 'syntaxes/test/dummy/ts.tmLanguage-dummy.json'],
    'testFile': 'syntaxes/test/data/inline-styles.ts',
  },
  {
    'name': 'template syntax',
    'scopeName': 'template.ng',
    'grammarFiles': ['syntaxes/template.json', 'syntaxes/expression.json'],
    'testFile': 'syntaxes/test/data/template.html',
  },
  {
    'name': 'block syntax',
    'scopeName': 'template.blocks.ng',
    'grammarFiles': [
      'syntaxes/template-blocks.json',
      'syntaxes/expression.json',
      'syntaxes/template.json',
    ],
    'testFile': 'syntaxes/test/data/template-blocks.html',
  },
  {
    'name': 'tag syntax',
    'scopeName': 'template.tag.ng',
    'grammarFiles': [
      'syntaxes/template-tag.json',
      'syntaxes/expression.json',
      'syntaxes/template.json',
    ],
    'testFile': 'syntaxes/test/data/template-tag.html',
  },
  {
    'name': 'expression syntax',
    'scopeName': 'template.ng',
    'grammarFiles': ['syntaxes/template.json', 'syntaxes/expression.json'],
    'testFile': 'syntaxes/test/data/expression.html',
  },
  {
    'name': 'let syntax',
    'scopeName': 'template.let.ng',
    'grammarFiles': ['syntaxes/let-declaration.json', 'syntaxes/expression.json'],
    'testFile': 'syntaxes/test/data/let-declaration.html',
  },
  {
    'name': 'host object literal',
    'scopeName': 'host-object-literal.ng',
    'grammarFiles': [
      'syntaxes/host-object-literal.json',
      'syntaxes/template.json',
      'syntaxes/expression.json',
    ],
    'testFile': 'syntaxes/test/data/host-object-literal.ts',
  },
  {
    'name': 'angular-ts fence language',
    'scopeName': 'source.angular-ts',
    'grammarFiles': [
      'syntaxes/angular-ts.json',
      'syntaxes/inline-template.json',
      'syntaxes/inline-styles.json',
      'syntaxes/host-object-literal.json',
      'syntaxes/template.json',
      'syntaxes/template-tag.json',
      'syntaxes/template-blocks.json',
      'syntaxes/let-declaration.json',
      'syntaxes/expression.json',
      'syntaxes/test/dummy/ts.tmLanguage-dummy.json',
    ],
    'testFile': 'syntaxes/test/data/angular-ts.ts',
  },
  {
    'name': 'angular-html fence language',
    'scopeName': 'text.angular-html',
    'grammarFiles': [
      'syntaxes/angular-html.json',
      'syntaxes/template.json',
      'syntaxes/template-tag.json',
      'syntaxes/template-blocks.json',
      'syntaxes/let-declaration.json',
      'syntaxes/expression.json',
    ],
    'testFile': 'syntaxes/test/data/angular-html.html',
  },
  {
    'name': 'markdown angular fences',
    'scopeName': 'text.html.markdown',
    'grammarFiles': [
      'syntaxes/markdown-fence.json',
      'syntaxes/angular-ts.json',
      'syntaxes/angular-html.json',
      'syntaxes/inline-template.json',
      'syntaxes/inline-styles.json',
      'syntaxes/host-object-literal.json',
      'syntaxes/template.json',
      'syntaxes/template-tag.json',
      'syntaxes/template-blocks.json',
      'syntaxes/let-declaration.json',
      'syntaxes/expression.json',
    ],
    'testFile': 'syntaxes/test/data/markdown-fence.md',
  },
];
